import { z } from "zod";

export const exitListParamsSchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  pageSize: z.coerce.number().int().positive().max(100).default(20),
  search: z.string().optional(),
  employeeId: z.string().uuid().optional().or(z.literal("")),
  departmentId: z.string().uuid().optional().or(z.literal("")),
  exitStatus: z
    .enum([
      "submitted",
      "manager_approved",
      "hr_approved",
      "clearance",
      "asset_return",
      "settlement",
      "interview",
      "documents",
      "completed",
      "rejected",
      "withdrawn",
      "",
    ])
    .optional(),
});

export const resignationFormSchema = z.object({
  employeeId: z.string().uuid(),
  resignationDate: z.string().min(1),
  lastWorkingDay: z.string().min(1),
  noticePeriodDays: z.coerce.number().int().min(0).max(365),
  reason: z.string().trim().min(2).max(200),
  comments: z.string().trim().max(2000).optional().nullable(),
});

export const resignationDecisionSchema = z.object({
  resignationId: z.string().uuid(),
  decision: z.enum(["approve", "reject"]),
  remarks: z.string().trim().max(2000).optional().nullable(),
  rejectedReason: z.string().trim().max(2000).optional().nullable(),
});

export const clearanceDecisionSchema = z.object({
  clearanceId: z.string().uuid(),
  clearanceStatus: z.enum(["approved", "rejected", "not_required"]),
  remarks: z.string().trim().max(2000).optional().nullable(),
});

export const assetReturnDecisionSchema = z.object({
  returnId: z.string().uuid(),
  returnStatus: z.enum(["returned", "damaged", "lost", "replacement_required"]),
  conditionNotes: z.string().trim().max(2000).optional().nullable(),
  recoveryAmount: z.coerce.number().min(0).optional().nullable(),
});

export const settlementFormSchema = z.object({
  resignationId: z.string().uuid(),
  pendingSalary: z.coerce.number().min(0),
  leaveEncashment: z.coerce.number().min(0),
  bonus: z.coerce.number().min(0),
  reimbursements: z.coerce.number().min(0),
  deductions: z.coerce.number().min(0),
  assetDamageRecovery: z.coerce.number().min(0),
  leaveBalanceDays: z.coerce.number().min(0),
  notes: z.string().trim().max(2000).optional().nullable(),
});

export const interviewFormSchema = z.object({
  resignationId: z.string().uuid(),
  reasonForLeaving: z.string().trim().max(2000).optional().nullable(),
  managerRating: z.coerce.number().int().min(1).max(5).optional().nullable(),
  workEnvironmentRating: z.coerce.number().int().min(1).max(5).optional().nullable(),
  salarySatisfactionRating: z.coerce.number().int().min(1).max(5).optional().nullable(),
  growthOpportunitiesRating: z.coerce.number().int().min(1).max(5).optional().nullable(),
  companyCultureRating: z.coerce.number().int().min(1).max(5).optional().nullable(),
  suggestions: z.string().trim().max(4000).optional().nullable(),
  overallRating: z.coerce.number().int().min(1).max(5).optional().nullable(),
  hrPrivateNotes: z.string().trim().max(4000).optional().nullable(),
});

export const exitSettingsSchema = z.object({
  defaultNoticePeriodDays: z.coerce.number().int().min(0).max(365),
  clearanceDepartments: z
    .array(
      z.object({
        key: z.string().trim().min(1).max(40),
        label: z.string().trim().min(1).max(80),
      }),
    )
    .min(1),
  enableExitInterview: z.boolean(),
  autoGenerateDocuments: z.boolean(),
  autoArchiveEmployee: z.boolean(),
  retentionPeriodDays: z.coerce.number().int().min(30).max(36500),
});

export type ExitListParams = z.infer<typeof exitListParamsSchema>;
export type ResignationFormValues = z.infer<typeof resignationFormSchema>;
export type ResignationDecisionValues = z.infer<typeof resignationDecisionSchema>;
export type ClearanceDecisionValues = z.infer<typeof clearanceDecisionSchema>;
export type AssetReturnDecisionValues = z.infer<typeof assetReturnDecisionSchema>;
export type SettlementFormValues = z.infer<typeof settlementFormSchema>;
export type InterviewFormValues = z.infer<typeof interviewFormSchema>;
export type ExitSettingsFormValues = z.infer<typeof exitSettingsSchema>;
export type ExitSettingsFormInput = z.input<typeof exitSettingsSchema>;
