import { hasAnyPermission } from "@/lib/permissions/utils";
import type { ExitAssetReturnStatus, ExitClearanceStatus, ExitSettlementStatus, ExitStatus } from "@/types/exit";

export const EXIT_ROUTES = {
  dashboard: "/dashboard/exit",
  resignations: "/dashboard/exit/resignations",
  clearance: "/dashboard/exit/clearance",
  assetReturn: "/dashboard/exit/assets",
  settlement: "/dashboard/exit/settlement",
  interview: "/dashboard/exit/interview",
  documents: "/dashboard/exit/documents",
  settings: "/dashboard/exit/settings",
} as const;

export const EXIT_SUB_NAV = [
  { title: "Dashboard", href: EXIT_ROUTES.dashboard },
  { title: "Resignations", href: EXIT_ROUTES.resignations },
  { title: "Clearance", href: EXIT_ROUTES.clearance },
  { title: "Asset Return", href: EXIT_ROUTES.assetReturn },
  { title: "Settlement", href: EXIT_ROUTES.settlement },
  { title: "Exit Interview", href: EXIT_ROUTES.interview },
  { title: "Documents", href: EXIT_ROUTES.documents },
  { title: "Settings", href: EXIT_ROUTES.settings },
] as const;

export const EXIT_STATUS_LABELS: Record<ExitStatus, string> = {
  submitted: "Submitted",
  manager_approved: "Manager Approved",
  hr_approved: "HR Approved",
  clearance: "Clearance",
  asset_return: "Asset Return",
  settlement: "Settlement",
  interview: "Exit Interview",
  documents: "Documents",
  completed: "Completed",
  rejected: "Rejected",
  withdrawn: "Withdrawn",
};

export const CLEARANCE_STATUS_LABELS: Record<ExitClearanceStatus, string> = {
  pending: "Pending",
  approved: "Approved",
  rejected: "Rejected",
  not_required: "Not Required",
};

export const ASSET_RETURN_STATUS_LABELS: Record<ExitAssetReturnStatus, string> = {
  pending: "Pending",
  returned: "Returned",
  damaged: "Damaged",
  lost: "Lost",
  replacement_required: "Replacement Required",
};

export const SETTLEMENT_STATUS_LABELS: Record<ExitSettlementStatus, string> = {
  draft: "Draft",
  pending: "Pending",
  approved: "Approved",
  paid: "Paid",
};

export const DEFAULT_EXIT_SETTINGS = {
  defaultNoticePeriodDays: 30,
  clearanceDepartments: [
    { key: "manager", label: "Reporting Manager" },
    { key: "hr", label: "HR" },
    { key: "it", label: "IT" },
    { key: "finance", label: "Finance" },
    { key: "admin", label: "Administration" },
  ],
  enableExitInterview: true,
  autoGenerateDocuments: true,
  autoArchiveEmployee: true,
  retentionPeriodDays: 2555,
} as const;

export const EXIT_REASON_OPTIONS = [
  "Better Opportunity",
  "Career Growth",
  "Compensation",
  "Relocation",
  "Personal Reasons",
  "Higher Education",
  "Health",
  "Work Environment",
  "Other",
] as const;

export function canViewExit(codes: string[]) {
  return hasAnyPermission(codes, ["exit.view"]);
}
export function canCreateExit(codes: string[]) {
  return hasAnyPermission(codes, ["exit.create"]);
}
export function canApproveExit(codes: string[]) {
  return hasAnyPermission(codes, ["exit.approve"]);
}
export function canClearanceExit(codes: string[]) {
  return hasAnyPermission(codes, ["exit.clearance", "exit.approve"]);
}
export function canSettlementExit(codes: string[]) {
  return hasAnyPermission(codes, ["exit.settlement"]);
}
export function canExitDocuments(codes: string[]) {
  return hasAnyPermission(codes, ["exit.documents", "exit.settlement"]);
}
export function canExitSettings(codes: string[]) {
  return hasAnyPermission(codes, ["exit.settings", "settings.manage"]);
}
