export type ExitStatus =
  | "submitted"
  | "manager_approved"
  | "hr_approved"
  | "clearance"
  | "asset_return"
  | "settlement"
  | "interview"
  | "documents"
  | "completed"
  | "rejected"
  | "withdrawn";

export type ExitClearanceStatus = "pending" | "approved" | "rejected" | "not_required";
export type ExitAssetReturnStatus =
  | "pending"
  | "returned"
  | "damaged"
  | "lost"
  | "replacement_required";
export type ExitSettlementStatus = "draft" | "pending" | "approved" | "paid";

export type ExitClearanceDepartment = { key: string; label: string };

export type ExitSettings = {
  defaultNoticePeriodDays: number;
  clearanceDepartments: ExitClearanceDepartment[];
  enableExitInterview: boolean;
  autoGenerateDocuments: boolean;
  autoArchiveEmployee: boolean;
  retentionPeriodDays: number;
};

export type ExitTimelineItem = {
  id: string;
  eventType: string;
  title: string;
  description: string | null;
  createdAt: string;
};

export type ExitClearanceItem = {
  id: string;
  resignationId: string;
  departmentKey: string;
  departmentLabel: string;
  clearanceStatus: ExitClearanceStatus;
  remarks: string | null;
  actedAt: string | null;
  sortOrder: number;
};

export type ExitAssetReturnItem = {
  id: string;
  resignationId: string;
  assetId: string | null;
  assignmentId: string | null;
  assetCode: string | null;
  assetName: string;
  categoryName: string | null;
  returnStatus: ExitAssetReturnStatus;
  conditionNotes: string | null;
  recoveryAmount: number;
  returnedAt: string | null;
};

export type ExitSettlementItem = {
  id: string;
  resignationId: string;
  employeeId: string;
  pendingSalary: number;
  leaveEncashment: number;
  bonus: number;
  reimbursements: number;
  deductions: number;
  assetDamageRecovery: number;
  netPayable: number;
  leaveBalanceDays: number;
  settlementStatus: ExitSettlementStatus;
  notes: string | null;
  approvedAt: string | null;
  paidAt: string | null;
};

export type ExitInterviewItem = {
  id: string;
  resignationId: string;
  employeeId: string;
  reasonForLeaving: string | null;
  managerRating: number | null;
  workEnvironmentRating: number | null;
  salarySatisfactionRating: number | null;
  growthOpportunitiesRating: number | null;
  companyCultureRating: number | null;
  suggestions: string | null;
  overallRating: number | null;
  hrPrivateNotes: string | null;
  conductedAt: string | null;
};

export type ExitResignationItem = {
  id: string;
  employeeId: string;
  employeeCode: string;
  employeeName: string;
  departmentName: string | null;
  designationTitle: string | null;
  resignationDate: string;
  lastWorkingDay: string;
  noticePeriodDays: number;
  reason: string;
  comments: string | null;
  exitStatus: ExitStatus;
  managerEmployeeId: string | null;
  managerName: string | null;
  managerActedAt: string | null;
  managerRemarks: string | null;
  hrActedAt: string | null;
  hrRemarks: string | null;
  ceoActedAt: string | null;
  ceoRemarks: string | null;
  rejectedReason: string | null;
  withdrawnAt: string | null;
  completedAt: string | null;
  createdAt: string;
  clearance?: ExitClearanceItem[];
  assets?: ExitAssetReturnItem[];
  settlement?: ExitSettlementItem | null;
  interview?: ExitInterviewItem | null;
  timeline?: ExitTimelineItem[];
};

export type ExitListResult = {
  data: ExitResignationItem[];
  total: number;
  page: number;
  pageSize: number;
};

export type ExitSummary = {
  pendingResignations: number;
  noticePeriod: number;
  pendingClearance: number;
  assetsPendingReturn: number;
  settlementsPending: number;
  leavingThisMonth: number;
  exitByDepartment: { departmentName: string; count: number }[];
  monthlyAttrition: { month: string; count: number }[];
  exitReasons: { reason: string; count: number }[];
  recentActivities: ExitTimelineItem[];
};

export type ExitLookups = {
  employees: { id: string; label: string }[];
  departments: { id: string; label: string }[];
};
