import type { AuthSupabaseClient } from "@/lib/auth/profile-loader";
import { DEFAULT_EXIT_SETTINGS } from "@/lib/exit/constants";
import type { ExitSettings } from "@/types/exit";
import type { ExitSettingsFormValues } from "@/lib/validations/exit";

export function mergeExitSettings(stored?: Partial<ExitSettings> | null): ExitSettings {
  const departments =
    Array.isArray(stored?.clearanceDepartments) && stored.clearanceDepartments.length
      ? stored.clearanceDepartments.map((d) => ({
          key: String(d.key),
          label: String(d.label),
        }))
      : DEFAULT_EXIT_SETTINGS.clearanceDepartments.map((d) => ({ ...d }));

  return {
    defaultNoticePeriodDays:
      Number(stored?.defaultNoticePeriodDays) || DEFAULT_EXIT_SETTINGS.defaultNoticePeriodDays,
    clearanceDepartments: departments,
    enableExitInterview: stored?.enableExitInterview !== false,
    autoGenerateDocuments: stored?.autoGenerateDocuments !== false,
    autoArchiveEmployee: stored?.autoArchiveEmployee !== false,
    retentionPeriodDays:
      Number(stored?.retentionPeriodDays) || DEFAULT_EXIT_SETTINGS.retentionPeriodDays,
  };
}

export async function getExitSettings(
  supabase: AuthSupabaseClient,
  organizationId: string,
): Promise<ExitSettings> {
  const { data, error } = await supabase
    .schema("hrms")
    .from("organization_settings")
    .select("settings")
    .eq("organization_id", organizationId)
    .is("deleted_at", null)
    .maybeSingle();

  if (error) throw new Error(error.message);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return mergeExitSettings((data?.settings as any)?.exit);
}

export async function updateExitSettings(
  supabase: AuthSupabaseClient,
  organizationId: string,
  userId: string,
  values: ExitSettingsFormValues,
): Promise<ExitSettings> {
  const nextSettings = mergeExitSettings(values);

  const { data: existing, error: existingError } = await supabase
    .schema("hrms")
    .from("organization_settings")
    .select("id, settings")
    .eq("organization_id", organizationId)
    .is("deleted_at", null)
    .maybeSingle();

  if (existingError) throw new Error(existingError.message);

  if (existing) {
    const current = (existing.settings as Record<string, unknown>) ?? {};
    const { error } = await supabase
      .schema("hrms")
      .from("organization_settings")
      .update({
        settings: { ...current, exit: nextSettings },
        updated_by: userId,
      })
      .eq("id", existing.id);
    if (error) throw new Error(error.message);
  } else {
    const { error } = await supabase.schema("hrms").from("organization_settings").insert({
      organization_id: organizationId,
      settings: { exit: nextSettings },
      status: "active",
      created_by: userId,
      updated_by: userId,
    });
    if (error) throw new Error(error.message);
  }

  return nextSettings;
}
