"use client";

import { format } from "date-fns";
import {
  CalendarClock,
  Download,
  Eye,
  Share2,
} from "lucide-react";
import { useMemo } from "react";
import {
  flexRender,
  getCoreRowModel,
  useReactTable,
  type ColumnDef,
} from "@tanstack/react-table";

import { Button } from "@/components/common/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import type { CeoReportLibraryRow } from "@/types/ceo-reports";

function formatBytes(bytes: number) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

type CeoReportsLibraryTableProps = {
  rows: CeoReportLibraryRow[];
  total: number;
  page: number;
  pageSize: number;
  isLoading?: boolean;
  onPageChange: (page: number) => void;
  onView: (runId: string) => void;
  onDownload: (runId: string) => void;
  onShare: (runId: string) => void;
  onSchedule: (reportKey: string) => void;
};

export function CeoReportsLibraryTable({
  rows,
  total,
  page,
  pageSize,
  isLoading,
  onPageChange,
  onView,
  onDownload,
  onShare,
  onSchedule,
}: CeoReportsLibraryTableProps) {
  const columns = useMemo<ColumnDef<CeoReportLibraryRow>[]>(
    () => [
      {
        accessorKey: "reportName",
        header: "Report Name",
        cell: ({ row }) => (
          <button
            type="button"
            className="font-medium text-primary hover:underline"
            onClick={() => onView(row.original.id)}
          >
            {row.original.reportName}
          </button>
        ),
      },
      { accessorKey: "categoryLabel", header: "Category" },
      {
        accessorKey: "departmentName",
        header: "Department",
        cell: ({ row }) => row.original.departmentName ?? "—",
      },
      {
        accessorKey: "generatedByName",
        header: "Generated By",
        cell: ({ row }) => row.original.generatedByName ?? "CEO",
      },
      {
        accessorKey: "createdAt",
        header: "Created Date",
        cell: ({ row }) =>
          format(new Date(row.original.createdAt), "dd MMM yyyy HH:mm"),
      },
      {
        accessorKey: "format",
        header: "Format",
        cell: ({ row }) => row.original.format.toUpperCase(),
      },
      {
        accessorKey: "status",
        header: "Status",
        cell: ({ row }) => (
          <span className="rounded-md bg-muted px-2 py-0.5 text-[11px] font-medium capitalize">
            {row.original.status}
          </span>
        ),
      },
      {
        accessorKey: "byteSize",
        header: "Size",
        cell: ({ row }) => formatBytes(row.original.byteSize),
      },
      {
        id: "actions",
        header: "Actions",
        cell: ({ row }) => (
          <div className="flex flex-wrap gap-1">
            <Button
              type="button"
              size="sm"
              variant="outline"
              onClick={() => onView(row.original.id)}
            >
              <Eye className="size-3.5" />
              View
            </Button>
            <Button
              type="button"
              size="sm"
              variant="outline"
              onClick={() => onDownload(row.original.id)}
              disabled={row.original.status !== "completed"}
            >
              <Download className="size-3.5" />
              Download
            </Button>
            <Button
              type="button"
              size="sm"
              variant="outline"
              onClick={() => onShare(row.original.id)}
            >
              <Share2 className="size-3.5" />
              Share
            </Button>
            <Button
              type="button"
              size="sm"
              variant="outline"
              onClick={() => onSchedule(row.original.reportKey)}
            >
              <CalendarClock className="size-3.5" />
              Schedule
            </Button>
          </div>
        ),
      },
    ],
    [onDownload, onSchedule, onShare, onView],
  );

  const table = useReactTable({
    data: rows,
    columns,
    getCoreRowModel: getCoreRowModel(),
  });

  const totalPages = Math.max(1, Math.ceil(total / pageSize));

  return (
    <section className="space-y-3">
      <div>
        <h2 className="text-sm font-semibold">Report Library</h2>
        <p className="text-xs text-muted-foreground">
          Generated executive reports available for preview, download, share, and schedule.
        </p>
      </div>

      <div className="overflow-hidden rounded-xl border bg-card shadow-sm">
        <Table>
          <TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header) => (
                  <TableHead key={header.id}>
                    {header.isPlaceholder
                      ? null
                      : flexRender(header.column.columnDef.header, header.getContext())}
                  </TableHead>
                ))}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {rows.length === 0 ? (
              <TableRow>
                <TableCell
                  colSpan={columns.length}
                  className="h-24 text-center text-muted-foreground"
                >
                  {isLoading
                    ? "Loading report library…"
                    : "No reports generated yet. Use Report Builder to create one."}
                </TableCell>
              </TableRow>
            ) : (
              table.getRowModel().rows.map((row) => (
                <TableRow key={row.id} className={isLoading ? "opacity-60" : undefined}>
                  {row.getVisibleCells().map((cell) => (
                    <TableCell key={cell.id}>
                      {flexRender(cell.column.columnDef.cell, cell.getContext())}
                    </TableCell>
                  ))}
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>

      <div className="flex items-center justify-between gap-3 text-sm">
        <p className="text-muted-foreground">
          Showing {rows.length === 0 ? 0 : (page - 1) * pageSize + 1}–
          {Math.min(page * pageSize, total)} of {total}
        </p>
        <div className="flex items-center gap-2">
          <Button
            type="button"
            size="sm"
            variant="outline"
            disabled={page <= 1 || isLoading}
            onClick={() => onPageChange(page - 1)}
          >
            Previous
          </Button>
          <span className="tabular-nums text-muted-foreground">
            {page} / {totalPages}
          </span>
          <Button
            type="button"
            size="sm"
            variant="outline"
            disabled={page >= totalPages || isLoading}
            onClick={() => onPageChange(page + 1)}
          >
            Next
          </Button>
        </div>
      </div>
    </section>
  );
}
