import { format } from "date-fns";

import {
  CeoChartPanel,
} from "@/components/ceo/ceo-module-primitives";
import type {
  CeoReportHistoryRow,
  CeoReportsInsights,
} from "@/types/ceo-reports";

export function CeoReportsHistory({ history }: { history: CeoReportHistoryRow[] }) {
  return (
    <section className="space-y-3">
      <div>
        <h2 className="text-sm font-semibold">Report History</h2>
        <p className="text-xs text-muted-foreground">
          Recent generation activity, status, and download counts.
        </p>
      </div>
      <div className="overflow-hidden rounded-xl border bg-card shadow-sm">
        <table className="w-full text-sm">
          <thead className="bg-muted/40 text-left text-xs uppercase tracking-wide text-muted-foreground">
            <tr>
              <th className="px-4 py-2.5 font-medium">Generation Date</th>
              <th className="px-4 py-2.5 font-medium">Report</th>
              <th className="px-4 py-2.5 font-medium">Generated By</th>
              <th className="px-4 py-2.5 font-medium">Status</th>
              <th className="px-4 py-2.5 font-medium">Download Count</th>
              <th className="px-4 py-2.5 font-medium">Last Downloaded</th>
            </tr>
          </thead>
          <tbody>
            {history.length === 0 ? (
              <tr>
                <td colSpan={6} className="px-4 py-8 text-center text-muted-foreground">
                  No report history yet.
                </td>
              </tr>
            ) : (
              history.map((item) => (
                <tr key={item.id} className="border-t">
                  <td className="px-4 py-2.5">
                    {format(new Date(item.generatedAt), "dd MMM yyyy HH:mm")}
                  </td>
                  <td className="px-4 py-2.5">{item.reportName}</td>
                  <td className="px-4 py-2.5">{item.generatedByName ?? "CEO"}</td>
                  <td className="px-4 py-2.5 capitalize">{item.status}</td>
                  <td className="px-4 py-2.5 tabular-nums">{item.downloadCount}</td>
                  <td className="px-4 py-2.5">
                    {item.lastDownloadedAt
                      ? format(new Date(item.lastDownloadedAt), "dd MMM yyyy")
                      : "—"}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </section>
  );
}

export function CeoReportsInsightsPanel({
  insights,
}: {
  insights: CeoReportsInsights;
}) {
  return (
    <section className="space-y-3">
      <div>
        <h2 className="text-sm font-semibold">Report Insights</h2>
        <p className="text-xs text-muted-foreground">
          Usage patterns across requested, downloaded, and departmental reports.
        </p>
      </div>
      <div className="grid gap-3 lg:grid-cols-2 xl:grid-cols-4">
        <CeoChartPanel title="Most Requested Reports" items={insights.mostRequested} />
        <CeoChartPanel
          title="Frequently Downloaded"
          items={insights.frequentlyDownloaded}
          color="bg-sky-500"
        />
        <CeoChartPanel
          title="Department Report Usage"
          items={insights.departmentUsage}
          color="bg-violet-500"
        />
        <CeoChartPanel
          title="Report Generation Trend"
          items={insights.generationTrend}
          color="bg-emerald-500"
        />
      </div>
    </section>
  );
}
