"use client";

import { format } from "date-fns";
import { Download, Loader2 } from "lucide-react";
import { useEffect, useState, useTransition } from "react";

import { Button } from "@/components/common/button";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import {
  downloadCeoReportAction,
  fetchCeoReportPreviewAction,
} from "@/lib/ceo/actions/ceo-reports-actions";
import type { CeoReportFormat, CeoReportPreview } from "@/types/ceo-reports";

type CeoReportsDrawerProps = {
  runId: string | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onDownloaded: () => void;
};

function downloadBase64(filename: string, mimeType: string, contentBase64: string) {
  const binary = atob(contentBase64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  const blob = new Blob([bytes], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

function Field({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="rounded-lg border bg-background/80 px-3 py-2.5">
      <p className="text-[10px] font-medium tracking-wide text-muted-foreground uppercase">
        {label}
      </p>
      <div className="mt-1 text-sm font-medium break-words">{value || "—"}</div>
    </div>
  );
}

export function CeoReportsDrawer({
  runId,
  open,
  onOpenChange,
  onDownloaded,
}: CeoReportsDrawerProps) {
  const [detail, setDetail] = useState<CeoReportPreview | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const [isActing, startActing] = useTransition();

  useEffect(() => {
    if (!open || !runId) {
      setDetail(null);
      setError(null);
      setMessage(null);
      return;
    }

    startTransition(async () => {
      const result = await fetchCeoReportPreviewAction({ runId });
      if (!result.success) {
        setDetail(null);
        setError(result.message);
        return;
      }
      setError(null);
      setDetail(result.data);
    });
  }, [open, runId]);

  function download(format?: CeoReportFormat) {
    if (!detail) return;
    startActing(async () => {
      const result = await downloadCeoReportAction({
        runId: detail.id,
        format,
      });
      if (!result.success) {
        setMessage(result.message);
        return;
      }
      if (result.filename && result.mimeType && result.contentBase64) {
        downloadBase64(result.filename, result.mimeType, result.contentBase64);
      }
      setMessage("Download started.");
      onDownloaded();
    });
  }

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="w-full overflow-y-auto sm:max-w-xl">
        <SheetHeader>
          <SheetTitle>Report Preview</SheetTitle>
        </SheetHeader>

        {isPending && !detail ? (
          <div className="flex items-center justify-center gap-2 py-16 text-sm text-muted-foreground">
            <Loader2 className="size-4 animate-spin" />
            Loading report…
          </div>
        ) : error ? (
          <p className="py-10 text-center text-sm text-destructive">{error}</p>
        ) : detail ? (
          <div className="mt-4 space-y-4">
            <div className="rounded-xl border bg-card p-4">
              <p className="text-lg font-semibold">{detail.reportName}</p>
              <p className="mt-1 text-sm text-muted-foreground">
                {detail.categoryLabel} · {detail.status}
              </p>
            </div>

            <section className="space-y-2">
              <h3 className="text-sm font-semibold">Report Summary</h3>
              <div className="grid gap-2 sm:grid-cols-2">
                <Field
                  label="Report Period"
                  value={
                    detail.periodFrom && detail.periodTo
                      ? `${detail.periodFrom} → ${detail.periodTo}`
                      : "—"
                  }
                />
                <Field
                  label="Generated On"
                  value={format(new Date(detail.generatedAt), "dd MMM yyyy HH:mm")}
                />
                <Field label="Generated By" value={detail.generatedByName ?? "CEO"} />
                <Field label="Rows" value={String(detail.rowCount)} />
              </div>
            </section>

            <section className="space-y-2">
              <h3 className="text-sm font-semibold">Data Sources</h3>
              <p className="rounded-lg border px-3 py-2.5 text-sm">
                {detail.dataSources.length > 0
                  ? detail.dataSources.join(", ")
                  : "—"}
              </p>
            </section>

            <section className="space-y-2">
              <h3 className="text-sm font-semibold">Key Insights</h3>
              {detail.keyInsights.length === 0 ? (
                <p className="text-sm text-muted-foreground">No insights recorded.</p>
              ) : (
                <ul className="space-y-1.5 text-sm">
                  {detail.keyInsights.map((insight) => (
                    <li key={insight} className="rounded-lg border px-3 py-2">
                      {insight}
                    </li>
                  ))}
                </ul>
              )}
            </section>

            <section className="space-y-2">
              <h3 className="text-sm font-semibold">Preview Pages</h3>
              {detail.previewRows.length === 0 ? (
                <p className="text-sm text-muted-foreground">No preview rows.</p>
              ) : (
                <div className="overflow-hidden rounded-xl border">
                  <table className="w-full text-sm">
                    <thead className="bg-muted/40 text-left text-xs uppercase tracking-wide text-muted-foreground">
                      <tr>
                        {Object.keys(detail.previewRows[0] ?? {}).map((key) => (
                          <th key={key} className="px-3 py-2 font-medium">
                            {key}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {detail.previewRows.map((row, index) => (
                        <tr key={index} className="border-t">
                          {Object.values(row).map((value, cellIndex) => (
                            <td key={cellIndex} className="px-3 py-2">
                              {value ?? "—"}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </section>

            <section className="space-y-2">
              <h3 className="text-sm font-semibold">Download Options</h3>
              <div className="flex flex-wrap gap-2">
                {(["pdf", "excel", "csv", "summary_pdf", "board_summary"] as CeoReportFormat[]).map(
                  (formatOption) => (
                    <Button
                      key={formatOption}
                      type="button"
                      size="sm"
                      variant="outline"
                      disabled={isActing}
                      onClick={() => download(formatOption)}
                    >
                      <Download className="size-3.5" />
                      {formatOption.replaceAll("_", " ").toUpperCase()}
                    </Button>
                  ),
                )}
              </div>
            </section>

            {message ? <p className="text-sm text-muted-foreground">{message}</p> : null}
          </div>
        ) : null}
      </SheetContent>
    </Sheet>
  );
}
