"use client";

import { format } from "date-fns";
import { Loader2 } from "lucide-react";
import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";

import { Button } from "@/components/common/button";
import {
  NotificationPriorityBadge,
  NotificationStatusBadge,
} from "@/components/notifications/notification-status-badge";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import {
  archiveCeoNotificationAction,
  fetchCeoNotificationDetailAction,
  markCeoNotificationReadAction,
  navigateCeoNotificationAction,
} from "@/lib/ceo/actions/ceo-notifications-actions";
import { formatNotificationDisplayText } from "@/lib/notifications/constants";
import type { CeoNotificationDetail } from "@/types/ceo-notifications";

type Props = {
  notificationId: string | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onChanged: () => void;
};

function Field({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="rounded-lg border bg-background/80 px-3 py-2.5">
      <p className="text-[10px] font-medium tracking-wide text-muted-foreground uppercase">
        {label}
      </p>
      <div className="mt-1 text-sm font-medium break-words">{value || "—"}</div>
    </div>
  );
}

export function CeoNotificationsDrawer({
  notificationId,
  open,
  onOpenChange,
  onChanged,
}: Props) {
  const router = useRouter();
  const [detail, setDetail] = useState<CeoNotificationDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const [isActing, startActing] = useTransition();

  function reload(id: string) {
    startTransition(async () => {
      const result = await fetchCeoNotificationDetailAction({ notificationId: id });
      if (!result.success) {
        setDetail(null);
        setError(result.message);
        return;
      }
      setError(null);
      setDetail(result.data);
    });
  }

  useEffect(() => {
    if (!open || !notificationId) {
      setDetail(null);
      setError(null);
      setMessage(null);
      return;
    }
    reload(notificationId);
  }, [open, notificationId]);

  function runAction(action: () => Promise<{ success: boolean; message: string }>) {
    startActing(async () => {
      const result = await action();
      setMessage(result.message);
      if (!result.success) return;
      if (notificationId) reload(notificationId);
      onChanged();
    });
  }

  function onNavigate(href: string) {
    if (!notificationId) return;
    startActing(async () => {
      const result = await navigateCeoNotificationAction({
        notificationId,
        href,
      });
      setMessage(result.message);
      if (!result.success) return;
      onChanged();
      onOpenChange(false);
      router.push(result.href ?? href);
    });
  }

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="w-full overflow-y-auto sm:max-w-lg">
        <SheetHeader>
          <SheetTitle>Notification Details</SheetTitle>
        </SheetHeader>

        {isPending && !detail ? (
          <div className="flex items-center justify-center py-16">
            <Loader2 className="size-5 animate-spin text-muted-foreground" />
          </div>
        ) : null}

        {error ? <p className="mt-4 text-sm text-destructive">{error}</p> : null}

        {detail ? (
          <div className="mt-4 space-y-4">
            <div>
              <h3 className="text-base font-semibold">
                {formatNotificationDisplayText(detail.item.title)}
              </h3>
              <p className="mt-1 text-sm text-muted-foreground">
                {formatNotificationDisplayText(detail.item.message)}
              </p>
            </div>

            <div className="grid gap-2 sm:grid-cols-2">
              <Field
                label="Priority"
                value={<NotificationPriorityBadge priority={detail.item.priority} />}
              />
              <Field
                label="Status"
                value={<NotificationStatusBadge status={detail.item.status} />}
              />
              <Field label="Generated By" value={detail.item.generatedByName} />
              <Field
                label="Created Time"
                value={format(new Date(detail.item.createdAt), "dd MMM yyyy HH:mm")}
              />
              <Field label="Related Employee" value={detail.item.employeeName} />
              <Field label="Related Department" value={detail.item.departmentName} />
              <Field label="Related Module" value={detail.relatedModuleLabel} />
              <Field label="Category" value={detail.item.categoryLabel} />
            </div>

            <section className="space-y-2">
              <h4 className="text-sm font-semibold">Timeline</h4>
              <ul className="space-y-2">
                {detail.timeline.map((event) => (
                  <li
                    key={event.id}
                    className="rounded-lg border px-3 py-2 text-sm"
                  >
                    <p className="font-medium">{event.label}</p>
                    <p className="text-xs text-muted-foreground">
                      {format(new Date(event.at), "dd MMM yyyy HH:mm")}
                      {event.detail ? ` · ${event.detail}` : ""}
                    </p>
                  </li>
                ))}
              </ul>
            </section>

            <section className="space-y-2">
              <h4 className="text-sm font-semibold">Supporting Information</h4>
              <div className="grid gap-2">
                {detail.supportingInfo.map((info) => (
                  <Field key={info.label} label={info.label} value={info.value} />
                ))}
              </div>
            </section>

            <section className="space-y-2">
              <h4 className="text-sm font-semibold">Quick Actions</h4>
              <div className="flex flex-wrap gap-2">
                {detail.quickActions.map((action) => (
                  <Button
                    key={action.id}
                    type="button"
                    size="sm"
                    variant="outline"
                    disabled={isActing}
                    onClick={() => onNavigate(action.href)}
                  >
                    {action.label}
                  </Button>
                ))}
                {detail.item.status === "unread" ? (
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    disabled={isActing}
                    onClick={() =>
                      runAction(() =>
                        markCeoNotificationReadAction({
                          notificationId: detail.item.id,
                        }),
                      )
                    }
                  >
                    Mark Read
                  </Button>
                ) : null}
                {detail.item.status !== "archived" ? (
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    disabled={isActing}
                    onClick={() =>
                      runAction(() =>
                        archiveCeoNotificationAction({
                          notificationId: detail.item.id,
                        }),
                      )
                    }
                  >
                    Archive
                  </Button>
                ) : null}
              </div>
            </section>

            {message ? (
              <p className="text-sm text-muted-foreground">{message}</p>
            ) : null}
          </div>
        ) : null}
      </SheetContent>
    </Sheet>
  );
}
