-- =============================================================================
-- Migration: storage_policies
-- Description: Superseded by 20260702150300_storage_policies_hosted_compat.sql
--
-- Original placeholder storage policies required COMMENT ON POLICY against
-- storage.objects, which fails on hosted Supabase (SQLSTATE 42501).
-- Policies are created in the successor migration without ownership operations.
-- =============================================================================
