import { formatPayrollMonthLabel } from "@/lib/payroll/services/payroll-utils";
import { PAYSLIP_ENGINE_NAME } from "@/lib/payroll/services/payslip-publication";
import {
  renderBrandedEmail,
  renderEmailButtons,
  renderParagraph,
} from "@/lib/email/branding";
import { sendEmail } from "@/lib/email/mailer";
import { PAYROLL_ROUTES } from "@/lib/payroll/constants";
import { siteConfig } from "@/config/site";
import type { PayslipDetail } from "@/types/payroll";

function payslipEmailHtml(payslip: PayslipDetail, downloadUrl: string): string {
  const month = formatPayrollMonthLabel(payslip.payrollMonth);
  const content = `
    ${renderParagraph(`Dear ${payslip.employee.firstName},`)}
    ${renderParagraph(
      `Your official salary statement for <strong>${month}</strong> has been published and is now available for download. Payslip reference: <strong>${payslip.payslipNumber}</strong>.`,
    )}
    ${renderEmailButtons([
      { label: "Download Payslip", href: downloadUrl, variant: "primary" },
    ])}
  `;

  return renderBrandedEmail({
    title: `Your Payslip for ${month} is Ready`,
    preheader: `Your payslip for ${month} is ready to download`,
    heading: `Your Payslip for ${month} is Ready`,
    contentHtml: content,
    footerNote: `Generated by ${PAYSLIP_ENGINE_NAME} · ${siteConfig.name}`,
  });
}

export async function sendPayslipReadyEmail(
  payslip: PayslipDetail,
  appOrigin: string,
): Promise<{ delivered: boolean; skipped?: boolean }> {
  const month = formatPayrollMonthLabel(payslip.payrollMonth);
  const { generatePayslipPdfBytes } = await import("@/lib/payroll/services/payslip-pdf");
  const pdfBytes = await generatePayslipPdfBytes(payslip);
  const downloadUrl = `${appOrigin}${PAYROLL_ROUTES.payslipDetail(payslip.id)}`;

  const result = await sendEmail({
    to: payslip.employee.email,
    subject: `Your Payslip for ${month} is Ready`,
    html: payslipEmailHtml(payslip, downloadUrl),
    attachments: [
      {
        filename: `Payslip-${month.replace(/\s+/g, "-")}-${payslip.employee.employeeCode}.pdf`,
        content: Buffer.from(pdfBytes),
        contentType: "application/pdf",
      },
    ],
  });

  return { delivered: result.delivered, skipped: "skipped" in result ? result.skipped : false };
}
