import { EMAIL_BRAND_LOGO_PATH } from "@/lib/brand/constants";
import { formatPayrollMonthLabel } from "@/lib/payroll/services/payroll-utils";
import { PAYSLIP_ENGINE_NAME } from "@/lib/payroll/services/payslip-publication";
import { sendEmail } from "@/lib/email/mailer";
import { PAYROLL_ROUTES } from "@/lib/payroll/constants";
import { siteConfig } from "@/config/site";
import type { PayslipDetail } from "@/types/payroll";

/** Email clients reject relative img URLs — always emit an absolute https URL. */
function resolveEmailLogoUrl(
  logoUrl: string | null | undefined,
  appOrigin: string,
): string {
  const fallback = `${appOrigin}${EMAIL_BRAND_LOGO_PATH}`;
  const value = logoUrl?.trim();
  if (!value) return fallback;
  if (
    value.startsWith("https://") ||
    value.startsWith("http://") ||
    value.startsWith("data:")
  ) {
    return value;
  }
  if (value.startsWith("/")) return `${appOrigin}${value}`;
  return fallback;
}

function payslipEmailHtml(payslip: PayslipDetail, downloadUrl: string, logoUrl: string): string {
  const month = formatPayrollMonthLabel(payslip.payrollMonth);
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f5;padding:32px 16px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border:1px solid #e4e4e7;border-radius:12px;overflow:hidden;">
        <tr><td align="center" style="padding:28px 36px 20px;border-bottom:1px solid #f0f0f2;text-align:center;">
          <img src="${logoUrl}" width="64" alt="${payslip.organization.name}" style="display:block;width:64px;height:auto;max-width:64px;border:0;border-radius:14px;margin:0 auto 14px;" />
          <p style="margin:0;font-size:11px;letter-spacing:0.14em;text-transform:uppercase;color:#71717a;">${payslip.organization.name}</p>
          <h1 style="margin:8px 0 0;font-size:22px;font-weight:600;color:#18181b;">Your Payslip for ${month} is Ready</h1>
        </td></tr>
        <tr><td style="padding:28px 36px;">
          <p style="margin:0 0 16px;font-size:15px;line-height:1.6;color:#3f3f46;">
            Dear ${payslip.employee.firstName},
          </p>
          <p style="margin:0 0 24px;font-size:15px;line-height:1.6;color:#3f3f46;">
            Your official salary statement for <strong>${month}</strong> has been published and is now available for download.
            Payslip reference: <strong>${payslip.payslipNumber}</strong>.
          </p>
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 8px;">
            <tr>
              <td align="center" style="text-align:center;">
                <a href="${downloadUrl}" style="display:inline-block;background:#5B21B6;color:#ffffff;text-decoration:none;font-size:14px;font-weight:600;padding:12px 24px;border-radius:8px;">
                  Download Payslip
                </a>
              </td>
            </tr>
          </table>
        </td></tr>
        <tr><td style="padding:20px 36px 28px;background:#fafafa;border-top:1px solid #f0f0f2;">
          <p style="margin:0;font-size:11px;line-height:1.5;color:#a1a1aa;">
            Generated by ${PAYSLIP_ENGINE_NAME} · ${siteConfig.name}
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

export async function sendPayslipReadyEmail(
  payslip: PayslipDetail,
  appOrigin: string,
): Promise<{ delivered: boolean; skipped?: boolean }> {
  const month = formatPayrollMonthLabel(payslip.payrollMonth);
  const { generatePayslipPdfBytes } = await import("@/lib/payroll/services/payslip-pdf");
  const pdfBytes = await generatePayslipPdfBytes(payslip);
  const downloadUrl = `${appOrigin}${PAYROLL_ROUTES.payslipDetail(payslip.id)}`;
  const logoUrl = resolveEmailLogoUrl(payslip.organization.logoUrl, appOrigin);

  const result = await sendEmail({
    to: payslip.employee.email,
    subject: `Your Payslip for ${month} is Ready`,
    html: payslipEmailHtml(payslip, downloadUrl, logoUrl),
    attachments: [
      {
        filename: `Payslip-${month.replace(/\s+/g, "-")}-${payslip.employee.employeeCode}.pdf`,
        content: Buffer.from(pdfBytes),
        contentType: "application/pdf",
      },
    ],
  });

  return { delivered: result.delivered, skipped: "skipped" in result ? result.skipped : false };
}
